add_newline = false

[container]
disabled = true

[hostname]
ssh_only = false
ssh_symbol = "ğŸŒ "
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false
