add_newline = false
command_timeout = 800
scan_timeout = 50

[container]
disabled = true

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = ""
format = '[@](cyan bold)[$hostname](white bold) '
disabled = false

[git_status]
style = "purple bold"
conflicted = 'ğŸ³'
stashed = ""
up_to_date = 'âœ“'
modified = '*'
staged = '[++\($count\)](green)'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
format = '([$all_status$ahead_behind]($style) )'

[package]
disabled = true

[nodejs]
disabled = true

[crystal]
disabled = true
